In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

## Loading Data

In [3]:
data = pd.read_csv('full_weaving_dataset.csv')

In [5]:
data.head()

,ID,Month,Construction,Req_Finish_Fabrics,Fabric_Allowance,Rec_Beam_length(yds),Shrink_allow,act_shrink%,Previous_pdn,Req_grey_fabric,Req_beam_length(yds),Total_pdn_m/c,Rej_and_cut_Piece,Total_pdn_per_order,warp_count,weft_count,epi,ppi
0,12207-8,January,40+40/2/40/110x80,31300,6.0,5752.336,12.5,12.26173158,5047,33297.87234,34797.6511,5047.0,0,0,double,80,110,80
1,12207-8,January,40+40/2/40/110x80,31300,6.0,5883.568,12.5,64.12041129,1952,33297.87234,34797.6511,2111.0,0,0,double,80,110,80
2,12207-8,January,40+40/2/40/110x80,31300,6.0,3094.888,12.5,24.13295732,2207,33297.87234,34797.6511,2348.0,0,0,double,80,110,80
3,12207-8,January,40+40/2/40/110x80,31300,6.0,5894.504,12.5,14.734132,5026,33297.87234,34797.6511,5026.0,0,0,double,80,110,80
4,12207-8,January,40+40/2/40/110x80,31300,6.0,5850.760,12.5,21.46319453,4391,33297.87234,34797.6511,4595.0,0,0,double,80,110,80

## Data Cleaning

#### Missing Value Handling

In [7]:
data.isnull().sum()

ID                          0
Month                       0
Construction                0
Req_Finish_Fabrics          0
Fabric_Allowance            0
Rec_Beam_length(yds)        0
Shrink_allow                0
act_shrink%                 0
Previous_pdn            13637
Req_grey_fabric             0
Req_beam_length(yds)        0
Total_pdn_m/c           13630
Rej_and_cut_Piece           0
Total_pdn_per_order         0
warp_count                  0
weft_count                  0
epi                         0
ppi                         0
dtype: int64

#### Removing the null values

In [8]:
data= data.dropna()

In [9]:
data.isnull().sum()

ID                      0
Month                   0
Construction            0
Req_Finish_Fabrics      0
Fabric_Allowance        0
Rec_Beam_length(yds)    0
Shrink_allow            0
act_shrink%             0
Previous_pdn            0
Req_grey_fabric         0
Req_beam_length(yds)    0
Total_pdn_m/c           0
Rej_and_cut_Piece       0
Total_pdn_per_order     0
warp_count              0
weft_count              0
epi                     0
ppi                     0
dtype: int64

#### Duplicate Value Handling

In [11]:
data.duplicated().sum()

np.int64(62648)

#### Removing the Duplicate Values

In [12]:
data = data.drop_duplicates()

In [13]:
data.duplicated().sum()

np.int64(0)

## Statistical Analysis

In [15]:
data.describe()

,Req_Finish_Fabrics,Fabric_Allowance,Rec_Beam_length(yds),Shrink_allow,Req_grey_fabric,Req_beam_length(yds),Total_pdn_m/c,Rej_and_cut_Piece,Total_pdn_per_order,weft_count,epi,ppi
count,44862.000000,44862.000000,44862.000000,44862.000000,44862.000000,44862.000000,4.486200e+04,44862.000000,44862.000000,44862.000000,44862.000000,44862.000000
mean,28172.417436,7.768053,4830.320772,12.699934,30269.156852,31644.543423,5.823320e+03,30.959141,3241.926709,73.016138,117.324373,84.190272
std,40172.379782,2.232077,15252.866728,2.604037,43164.250649,45090.714194,5.682555e+04,299.489898,29402.108033,1134.883253,12.630247,8.840724
min,50.000000,5.000000,0.000000,6.000000,54.347826,56.473019,0.000000e+00,0.000000,0.000000,20.000000,30.000000,42.000000
25%,3000.000000,7.000000,2036.283200,10.200000,3271.537623,3439.871745,4.920000e+02,0.000000,0.000000,40.000000,110.000000,80.000000
50%,8885.000000,7.000000,2597.300000,13.500000,9452.127660,9860.470134,1.220000e+03,0.000000,0.000000,40.000000,120.000000,90.000000
75%,40085.000000,8.000000,3237.056000,14.200000,43102.150540,45048.674950,2.045000e+03,0.000000,0.000000,40.000000,120.000000,90.000000
max,172800.000000,44.000000,292116.964000,40.800000,192427.616900,211997.533200,1.878576e+06,11353.000000,924098.000000,40140.000000,170.000000,110.000000